### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by LigZhong** [hitachinsk/ISVI#1]
Hi, thank you for your great job; the demo is really interesting. Are you going to release the code at some point?

**Comment by hitachinsk** [comment]
Sorry for the late reply. Thanks for your interest in our work. In these days, I am trying my best to clean our codes and the codes will be released before the AAAI submission time circle.

**Comment by quhaoooo** [comment]
hi~ , are there any plan to release the code recently?

**Comment by hitachinsk** [comment]
The codes have been released, thanks for your attention to our work.
